const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

// The ABI is generated by Hardhat when you run `npm run compile` in the
// contracts project root. This path assumes the standard project layout:
//   credchain/
//     artifacts/contracts/CredentialRegistry.sol/CredentialRegistry.json
//     backend/blockchain.js   <-- this file
const artifactPath = path.join(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "CredentialRegistry.sol",
  "CredentialRegistry.json",
);

if (!fs.existsSync(artifactPath)) {
  console.warn(
    "⚠️  Contract artifact not found. Run `npm run compile` (and deploy it) " +
      "in the credchain root folder before starting the backend.",
  );
}

const contractArtifact = fs.existsSync(artifactPath)
  ? JSON.parse(fs.readFileSync(artifactPath, "utf8"))
  : null;

const provider = new ethers.JsonRpcProvider(
  process.env.RPC_URL || "http://127.0.0.1:8545",
);

// Wrapped in NonceManager: without this, firing several transactions back-to-back
// from the same wallet can hit a stale/cached nonce from the provider and fail
// with "Nonce too low" / "nonce has already been used". NonceManager tracks the
// nonce locally instead of re-querying the network for every transaction.
const signer = process.env.ISSUER_PRIVATE_KEY
  ? new ethers.NonceManager(
      new ethers.Wallet(process.env.ISSUER_PRIVATE_KEY, provider),
    )
  : null;

let contract = null;
if (contractArtifact && process.env.CONTRACT_ADDRESS && signer) {
  contract = new ethers.Contract(
    process.env.CONTRACT_ADDRESS,
    contractArtifact.abi,
    signer,
  );
}

function requireContract() {
  if (!contract) {
    throw new Error(
      "Smart contract is not configured. Check backend/.env has CONTRACT_ADDRESS " +
        "and ISSUER_PRIVATE_KEY set, and that the contract has been deployed.",
    );
  }
  return contract;
}

/** Deterministically hash the off-chain credential data so it can be compared on-chain. */
function hashCredentialData(data) {
  const json = JSON.stringify(data);
  return ethers.keccak256(ethers.toUtf8Bytes(json));
}

/** Turn a human-readable credential ID (e.g. "ABC12345") into a bytes32 the contract expects. */
function idToBytes32(id) {
  return ethers.keccak256(ethers.toUtf8Bytes(id));
}

async function issueOnChain(id, data) {
  const c = requireContract();
  const dataHash = hashCredentialData(data);
  const tx = await c.issueCredential(idToBytes32(id), dataHash);
  const receipt = await tx.wait();
  return { txHash: tx.hash, dataHash, blockNumber: receipt.blockNumber };
}

async function revokeOnChain(id) {
  const c = requireContract();
  const tx = await c.revokeCredential(idToBytes32(id));
  await tx.wait();
  return { txHash: tx.hash };
}

async function getOnChainRecord(id) {
  const c = requireContract();
  const [dataHash, issuer, status, issuedAt, revokedAt] = await c.getCredential(
    idToBytes32(id),
  );
  const statusMap = ["None", "Valid", "Revoked"];
  return {
    dataHash,
    issuer,
    status: statusMap[Number(status)],
    issuedAt: Number(issuedAt),
    revokedAt: Number(revokedAt),
  };
}

module.exports = {
  hashCredentialData,
  idToBytes32,
  issueOnChain,
  revokeOnChain,
  getOnChainRecord,
};
